plugins {
    alias(libs.plugins.android.application)
    id("com.chaquo.python")
}




android {
    flavorDimensions "pyVersion"
    productFlavors {
        create("py313") { dimension = "pyVersion" }
    }
    chaquopy {
        defaultConfig {

            buildPython "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3"


            sourceSets {
                getByName("main") {
                    srcDir("src/main/python")
                }
            }
            version = "3.13"

        }
        productFlavors {
            getByName("py313") { version = "3.13" }
        }
        sourceSets {}
    }
    namespace = "com.example.aviation"
    compileSdk = 35


    defaultConfig {
        applicationId = "com.example.aviation"
        minSdk = 31
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a"
        }





    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles(
                    getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }



}
dependencies {

    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.activity)
    implementation(libs.constraintlayout)
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)

}